# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 501587c3d2bad7f4bdfb3ae9ce0b39a38b381e044c77ed00540d88937a6109d923ecaf48833b8366870a895704cd7a4c18552fa1baf8467a227537cb4c0d516b

test:
  secret_key_base: 45e313f6dc297abdf7bbba2ba50644244c5af2a75d6fb6d3f7997e18507c6c3513f2dbb2cb8bfd0d6182d5798f830d2529ed13d7843123b98236d2fbec75f35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
